/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Beach = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Attraction = IDL.Record({
  'tip' : IDL.Opt(IDL.Text),
  'hours' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'admission' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const Tip = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
export const Island = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'beaches' : IDL.Vec(Beach),
  'topAttractions' : IDL.Vec(Attraction),
  'travelTips' : IDL.Vec(Tip),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllIslands' : IDL.Func([], [IDL.Vec(Island)], ['query']),
  'getIslandByName' : IDL.Func([IDL.Text], [Island], ['query']),
  'initializeIslands' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Beach = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Attraction = IDL.Record({
    'tip' : IDL.Opt(IDL.Text),
    'hours' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'admission' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const Tip = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const Island = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'beaches' : IDL.Vec(Beach),
    'topAttractions' : IDL.Vec(Attraction),
    'travelTips' : IDL.Vec(Tip),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllIslands' : IDL.Func([], [IDL.Vec(Island)], ['query']),
    'getIslandByName' : IDL.Func([IDL.Text], [Island], ['query']),
    'initializeIslands' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };